import AuthGuard from '@/components/AuthGuard/AuthGuard';
import type { Metadata } from 'next';

import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthorizedLayout({ children }: PropsWithChildren) {
  return <AuthGuard>{children}</AuthGuard>;
}
