import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function UnauthorizedLayout({ children }: PropsWithChildren) {
  return <section className="unauthorized-layout">{children}</section>;
}
