import type { Metadata } from 'next';
import './../../globals.css';
import AppProviders from '@/providers/AppProviders';
import { PropsWithChildren } from 'react';
import StickyHeader from '@/components/Header/StickyHeader';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <StickyHeader />
          {children}
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
